from __future__ import annotations

MAX_IPC_MESSAGE_BYTES = 262_144
MAX_AUTH_MESSAGE_BYTES = 16_384
PIPE_BUFFER_BYTES = 65_536
PIPE_PREFIX = "codex-serverops"
IPC_HANDSHAKE_TIMEOUT_SECONDS = 5.0
IPC_FRAME_TIMEOUT_SECONDS = 5.0
